# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

altern_Craw <- function(x, k, i0, i1) {
    .Call(`_SignDepth_altern_Craw`, x, k, i0, i1)
}

altern_Craw2 <- function(x, k) {
    .Call(`_SignDepth_altern_Craw2`, x, k)
}

compKdepth <- function(x, K) {
    .Call(`_SignDepth_compKdepth`, x, K)
}

kSD_Craw2 <- function(ord, sgn, k, echo) {
    .Call(`_SignDepth_kSD_Craw2`, ord, sgn, k, echo)
}

triangle <- function(si, sj, sk, ri, rj, rk) {
    .Call(`_SignDepth_triangle`, si, sj, sk, ri, rj, rk)
}

kSD_Cfull2 <- function(x, rnk) {
    .Call(`_SignDepth_kSD_Cfull2`, x, rnk)
}

testtriangle <- function(ri, rj, rk, rl, tp) {
    .Call(`_SignDepth_testtriangle`, ri, rj, rk, rl, tp)
}

kSD_Cfull <- function(x, rnk) {
    .Call(`_SignDepth_kSD_Cfull`, x, rnk)
}

C123 <- function(a, b, c) {
    .Call(`_SignDepth_C123`, a, b, c)
}

C132 <- function(a, b, c) {
    .Call(`_SignDepth_C132`, a, b, c)
}

C312 <- function(a, b, c) {
    .Call(`_SignDepth_C312`, a, b, c)
}

kSD_Cfull4 <- function(s, r) {
    .Call(`_SignDepth_kSD_Cfull4`, s, r)
}

